#!/usr/bin/awk -f

BEGIN {
    print "digraph G {"
    print "size=\"7.5,10\""
#    print "ranksep=\"equally\""
    print "node [label=\"\", shape=circle, fontsize=18]"
    print "edge [fontsize=48]"
}

{
    state = "start"
    for ( i = 1 ; i <= length($1) ; i++) {
	char = substr($1, i, 1)
	nextstate = substr($1, 1, i)	
	arc = state " " nextstate
	if (! (arc in arcs)) {
	    arcs[arc] = ""
	    print state " -> " nextstate " [ label=\" " char "\"]"
	}
	state = nextstate
    }
    print "subgraph cluster" $1 " {"
    print "labelloc=b"
    print "color=white"
    print "fontsize=36"
    print "label=\"" $1 "\""
    print $1 " [ shape=doublecircle ]"
    print "}"

}

END {
    print "}"	
}
